with-expecter: true
disable-version-string: true
mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceNameSnake}}.go"
outpkg: "{{.PackageName}}"
dir: mocks/{{.PackageName}}
packages:
    github.com/ilfey/hikilist-go/pkg/parser/extractor:
        interfaces:
            AnimeExtractor:
    github.com/ilfey/hikilist-go/pkg/parser/statistic:
        interfaces:
            RW:
            