package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/ilfey/hikilist-go/internal/domain/agg"
	"github.com/ilfey/hikilist-go/internal/domain/types"
	"github.com/ilfey/hikilist-go/internal/infrastucture/api/controller/graph/exec"
)

// Animes is the resolver for the animes field.
func (r *pageResolver) Animes(ctx context.Context, obj *agg.Page, order *types.Order) ([]agg.Anime, error) {
	o := types.Order("-id")

	if order != nil {
		o = *order
	}

	obj.Info.Pagination.Order = o

	animes, err := r.anime.service.Find(ctx, obj.Info.Pagination)
	if err != nil {
		return nil, r.log.Propagate(err)
	}

	return animes, nil
}

// Page returns exec.PageResolver implementation.
func (r *Resolver) Page() exec.PageResolver { return &pageResolver{r} }

type pageResolver struct{ *Resolver }
