// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package agg

import (
	"github.com/ilfey/hikilist-go/internal/domain/dto"
)

type Page struct {
	Info   *PageInfo `json:"info"`
	Animes []Anime   `json:"animes,omitempty"`
}

type PageInfo struct {
	Pagination *dto.PaginationRequestDTO `json:"pagination"`
}
